# Generated by Django 3.2.6 on 2022-12-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
